# Generated by Django 3.1.7 on 2021-03-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('food_group', models.CharField(max_length=100)),
                ('calories', models.IntegerField()),
                ('fat', models.DecimalField(decimal_places=2, max_digits=6)),
                ('protein', models.DecimalField(decimal_places=2, max_digits=6)),
                ('net_carbs', models.DecimalField(decimal_places=2, max_digits=6)),
                ('serving_weight', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
