# Generated by Django 3.1.7 on 2021-03-22 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_consumedfood'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumedfood',
            old_name='user',
            new_name='consumer',
        ),
    ]
